Fix: Compose Compiler version compatibility with Kotlin 1.9.24
Update kotlinCompilerExtensionVersion from 1.5.4 to 1.5.14

Kotlin 1.9.24 requires Compose Compiler 1.5.14+
The old version 1.5.4 was built for Kotlin 1.9.20 only.

This fixes the compilation error:
'This version (1.5.4) of the Compose Compiler requires Kotlin version 1.9.20
but you appear to be using Kotlin version 1.9.24'

Reference: https://developer.android.com/jetpack/androidx/releases/compose-compiler